# version: '3'

# services:
#   locust-master:
#     image: locustio/locust
#     ports:
#       - "8089:8089"
#     volumes:
#       - ./:/mnt/locust
#     command: -f /mnt/locust/locustfile.py --master --host http://host.docker.internal:8000

#   locust-worker:
#     image: locustio/locust
#     volumes:
#       - ./:/mnt/locust
#     command: -f /mnt/locust/locustfile.py --worker --master-host locust-master
#     depends_on:
#       - locust-master

services:
  locust-master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master --host http://host.docker.internal:8080

  locust-worker-1:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master

  locust-worker-2:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master

  locust-worker-3:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master
